environments:
  prod:
    secrets:
    - "envs/{{ .Environment.Name }}/secrets.yaml"
    values:
    - "envs/values.yaml"
    - "envs/{{ .Environment.Name }}/values.yaml"

repositories:
- name: ingress-nginx
  url: "https://kubernetes.github.io/ingress-nginx"
- name: jetstack 
  url: https://charts.jetstack.io

helmDefaults:
  wait: true
  timeout: 60
  atomic: true
  skipDeps: true
  cleanupOnFail: false
  kubeContext: {{ requiredEnv "KUBE_CONTEXT" }}

releases:
- name: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  values:
  - controller:
      metrics:
        enabled: true
      service:
        enabled: true
        type: ClusterIP
        externalIPs: 
{{ toYaml .Values.externalIPs | indent 8 }}
      nodeSelector: 
{{ toYaml .Values.nodeSelectors.alwaysOn | indent 8 }}
- name: cert-manager
  chart: jetstack/cert-manager
  installed: false
  values:
  - nodeSelector: 
{{ toYaml .Values.nodeSelectors.alwaysOn | indent 6 }}
    webhook:
      nodeSelector:
{{ toYaml .Values.nodeSelectors.alwaysOn | indent 8 }}
    cainjector:
      nodeSelector:
{{ toYaml .Values.nodeSelectors.alwaysOn | indent 8 }}
  set:
  - name: installCRDs
    value: true
  - name: ingressShim.defaultIssuerName
    value: letsencrypt
  - name: ingressShim.defaultIssuerKind
    value: ClusterIssuer
  - name: ingressShim.defaultIssuerGroup
    value: cert-manager.io
- name: cert-manager-issuers
  chart: ../charts/cert-manager-issuers
  values:
  - email: eunchul.dev@gmail.com
